name: OWASP ZAP Scan

on:
  push:
    branches:
      - zap
  workflow_dispatch:

jobs:
  zap-scan:
    name: OWASP ZAP Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        
      - uses: JarvusInnovations/background-action@v1
        name: Bootstrap System Under Test (SUT)
        with:
          run: "./gradlew run && echo foobar"
          wait-on: "http-get://localhost:8080"
          tail: true # true = stderr,stdout
          log-output-resume: stderr
          wait-for: 2m
          log-output: stderr,stdout # same as true
          log-output-if: failure

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.15.0
        with:
          target: 'http://localhost:8080'
